### ISSUE TITLE
ENABLE_SCHEDULING parameter missing in OS template

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-firehose-fetcher#12]
`ENABLE_SCHEDULING` parameter needs to be listed here: https://github.com/fabric8-analytics/fabric8-analytics-firehose-fetcher/blob/master/openshift/template.yaml#L120-L143

Otherwise the value cannot be configured during deployment.

**Comment by msrb** [comment]
cc @pkajaba :)

**Comment by pkajaba** [comment]
Thanks for letting me know.
