### ISSUE TITLE
Report only ecosystems that we currently support

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-firehose-fetcher#16]
I can see log messages that report rubygems updates:
```
2017-09-11 21:17:25,241 - f8a_firehose_fetcher.firehose_fetcher - INFO - Received event for EPV: 'rubygems':'websocket-driver':'0.7.0'
```

I haven't checked the source code, but hopefully we are not scheduling analyses for rubygems (we do not support them yet). We should suppress these messages since they are confusing.

**Comment by pkajaba** [comment]
We are not scheduling unsupported ecosystems. it's just log that we received an update of that package but we don't do anything else.
